# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/twirp.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/twirp.proto", :syntax => :proto3) do
    add_message "sourced_store.twirp_transport.ReadStreamRequest" do
      optional :stream_id, :string, 1
    end
    add_message "sourced_store.twirp_transport.ReadStreamResponse" do
      repeated :events, :message, 1, "sourced_store.twirp_transport.Event"
    end
    add_message "sourced_store.twirp_transport.Event" do
      optional :stream_id, :string, 1
      optional :topic, :string, 2
      map :payload, :string, :string, 3
    end
  end
end

module SourcedClient
  module TwirpTransport
    ReadStreamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sourced_store.twirp_transport.ReadStreamRequest").msgclass
    ReadStreamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sourced_store.twirp_transport.ReadStreamResponse").msgclass
    Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sourced_store.twirp_transport.Event").msgclass
  end
end
