# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'twirp_pb.rb'

module TwirpTransport
  class EventStoreService < Twirp::Service
    package 'twirp_transport'
    service 'EventStore'
    rpc :ReadStream, ReadStreamRequest, ReadStreamResponse, :ruby_method => :read_stream
  end

  class EventStoreClient < Twirp::Client
    client_for EventStoreService
  end
end
